name: Release - cli

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint-all:
    if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: node ./bin/npm-cli.js run resetdeps
      - run: node ./bin/npm-cli.js run lint-all

  prepublish:
    if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: make prepublish

  test-all:
    if:  startsWith(github.head_ref, 'release/')
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 12.13.0
          - 12.x
          - 14.15.0
          - 14.x
          - 16.0.0
          - 16.x
        platform:
          - os: ubuntu-latest
            shell: bash
          - os: macos-latest
            shell: bash
          - os: windows-latest
            shell: cmd
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - run: node ./bin/npm-cli.js run resetdeps
    - run: node ./bin/npm-cli.js run test-all --ignore-scripts
    - name: git status
      if: matrix.platform.os != 'windows-latest'
      run: node scripts/git-dirty.js
